version: '3.8'

services:
  frontend-blue:
    build: .
    container_name: react-frontend-blue
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits CPU usage to 50%
          memory: '512M' # Limits memory usage to 512MB

  frontend-green:
    build: .
    container_name: react-frontend-green
    restart: always
    ports:
      - "3001:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits CPU usage to 50%
          memory: '512M' # Limits memory usage to 512MB

networks:
  app-network:
    external: true
